"""new fields in user model

Revision ID: 1446690cb089
Revises: ed9687d8da1c
Create Date: 2024-04-15 16:23:21.393538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1446690cb089'
down_revision = 'ed9687d8da1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('info', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('lastlogin', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastlogin')
        batch_op.drop_column('info')

    # ### end Alembic commands ###
